# Generated by Django 5.0.6 on 2024-06-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='name',
            field=models.CharField(default='John Doe', max_length=100),
        ),
    ]
